#!/usr/bin/python3
from sys import argv, exit


def factorize(number_to_check):
    """Find two small numbers that multiply to give a given number.

    Args:
        number_to_check (int): The number to factorize.
    """
    i = 2

    if number_to_check < 2:
        return

    while number_to_check % i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(number_to_check, number_to_check / i, i))


if __name__ == "__main__":
    if len(argv) != 2:
        exit()

    try:
        with open(argv[1]) as file:
            line = file.readline()

            while line:
                number_to_check = int(line.strip())
                factorize(number_to_check)
                line = file.readline()
    except FileNotFoundError:
        pass
