#!/usr/bin/python3
import sys


def factorize(num):
    """Factorize a number into two factors.

    Args:
        num (int): The number to factorize.

    Returns:
        tuple: A tuple containing the two factors.
    """
    factor1 = 2
    while num % factor1:
        factor1 += 1

    factor2 = num // factor1
    return factor2, factor1


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(f"Wrong usage: {sys.argv[0]} <file_path>")

    filename = sys.argv[1]

    try:
        with open(filename, 'r') as file:
            for line in file:
                num = int(line.strip())
                factor2, factor1 = factorize(num)
                print(f"{num} = {factor2} * {factor1}")
    except FileNotFoundError:
        sys.exit(f"File not found: {filename}")
