#!/usr/bin/env python

import sys

def factorize(num):
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return i, num // i
    return None, None

def main(input_file):
    with open(input_file, 'r') as file:
        for line in file:
            num = int(line.strip())
            factor1, factor2 = factorize(num)
            if factor1 is not None:
                print(f"{num}={factor1}*{factor2}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: ./factors <file>")
        sys.exit(1)
    
    input_file = sys.argv[1]
    main(input_file)