#!/usr/bin/python3
import sys


def factorize():
    """
    Factorizes the given numbers into two prime factors.
    """
    try:
        file_name = sys.argv[1]
        with open(file_name) as file:
            for line in file:
                num = int(line.strip())
                factor_found = False

                if num % 2 == 0:
                    print("{}={}*{}".format(num, num // 2, 2))
                    continue

                factor = 3
                while factor * factor <= num:
                    if num % factor == 0:
                        factor_found = True
                        print("{}={}*{}".format(num, num // factor, factor))
                        break
                    factor += 2
                
                if not factor_found:
                    print("{}={}*{}".format(num, num, 1))

    except (IndexError, FileNotFoundError):
        pass


if __name__ == "__main__":
    factorize()